name: .NET CI/CD

on:
  push:
    branches:
      - main   # ⚠️ tumhara branch main hai

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:

    # Checkout
    - name: Checkout code
      uses: actions/checkout@v4

    # Restore
    - name: Restore dependencies
      run: dotnet restore

    # Build
    - name: Build project
      run: dotnet build --configuration Release --no-restore

    # Publish
    - name: Publish project
      run: dotnet publish -c Release -o publish

    # Stop IIS (IMPORTANT)
    - name: Stop IIS
      shell: powershell
      run: iisreset /stop

    # Ensure folder exists
    - name: Ensure IIS Folder Exists
      shell: powershell
      run: |
        if (!(Test-Path "C:\inetpub\wwwroot\SalesDashboardAPI")) {
            New-Item -ItemType Directory -Path "C:\inetpub\wwwroot\SalesDashboardAPI"
        }

    # Clean folder
    - name: Clean IIS Folder
      shell: powershell
      run: |
        if (Test-Path "C:\inetpub\wwwroot\SalesDashboardAPI") {
            Get-ChildItem "C:\inetpub\wwwroot\SalesDashboardAPI" -Recurse | Remove-Item -Force -Recurse -ErrorAction SilentlyContinue
        }

    # Copy files
    - name: Copy Files to IIS
      shell: powershell
      run: |
        Copy-Item -Path "publish\*" -Destination "C:\inetpub\wwwroot\SalesDashboardAPI" -Recurse -Force

    # Start IIS
    - name: Start IIS Site
      shell: powershell
      run: |
        Import-Module WebAdministration
        if (Get-Website -Name "SalesDashboardAPI" -ErrorAction SilentlyContinue) {
            Start-WebSite -Name "SalesDashboardAPI"
        }

    # Final restart (optional but safe)
    - name: Restart IIS
      shell: powershell
      run: iisreset /start
